sudo: required

services:
  - docker

before_install:
  - docker pull java:8-jre-alpine

env:
  global:
    - LIQUIBASE=3.3.9
    - POSTGRES=9.3.1102.jdbc41

script:
  - chmod +x ./build.sh
  - ./build.sh ${LIQUIBASE} ${POSTGRES}

before_deploy:
  - docker login \
      --username ${DOCKER_USERNAME} \
      --password ${DOCKER_PASSWORD}

deploy:

  - provider: script
    script: docker push aetheric/liquibase
    skip_cleanup: true
    on:
      branch: postgres

